name: Build

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      
      - name: Set up docker environment
        run: docker compose up -d

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
      
      - name: Clean docker environment
        run: docker compose down --rmi all -v --remove-orphans

  versioning:
    permissions:
      contents: write
    needs: test
    runs-on:
      ubuntu-latest
    outputs:
      version: ${{ steps.latest_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Git Identity
        run: |
          git checkout main
          git fetch --all --tags
          git config --global user.email "antoniojosedonishung@gmail.com"
          git config --global user.name "Antonio Donis"
      
      - name: Setup node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
        
      - name: Changelog
        run: 'npx standard-version --message "[ci skip] chore(release): %s"'

      - name: Push changes
        run: git push --follow-tags --force origin main

      - id: latest_version
        name: Latest version
        run: python version.py >> $GITHUB_OUTPUT

  release-github:
    permissions:
      contents: write
      packages: write
    needs:
      - versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{needs.versioning.outputs.version}}